name: Extract IPA

on:
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Unpack and Dump
        run: |
          ls -la
          if [ -f "Droze.ipa" ]; then
            echo "Файл Droze.ipa найден!"
            unzip -q Droze.ipa -d extracted/
            APP_PATH=$(find extracted/Payload -name "*.app" | head -n 1)
            BINARY="$APP_PATH/$(basename "$APP_PATH" .app)"
            strings "$BINARY" > strings_dump.txt
            mkdir -p output
            mv strings_dump.txt output/
          else
            echo "Ошибка: файл Droze.ipa не найден в корне репозитория!"
            exit 1
          fi

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: dump
          path: output/
